In [23]:
import requests
import time
# url = 'http://www.kbreport.com/leader/main' #실제 url
url = 'http://www.kbreport.com/leader/list/ajax' #ajax 요청
param = {"rows":"20",
         "order":"oWAR",
         "orderType":"DESC",
         "teamId":"",
         "defense_no":"",
         "year_from":"2020",
         "year_to":"2020",
         "gameType":"",
         "split01":"",
         "split02_1":"",
         "split02_2":"",
         "r_tpa_count":"",
         "tpa_count":"",
         "page":1}

pd_list = []
page = 1
while True:
    print(page, end=', ')
    param['page']=page
    res = requests.post(url, data=param)
    if res.status_code == 200:
        df = pd.read_html(res.text, index_col='#')[0]
        if df.shape[0] == 0: #조회결과가 없으면 행이 (0, 20) shape이다.
            break
        pd_list.append(df)
        page+=1
        time.sleep(1)

1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,

In [24]:
pd.concat(pd_list, axis=0)#.reset_index(drop=True)

,선수명,팀명,경기,타석,타수,안타,홈런,득점,타점,볼넷,삼진,도루,BABIP,타율,출루율,장타율,OPS,wOBA,WAR
#,,,,,,,,,,,,,,,,,,,
1,로하스,KT,56,249,227,85,19,50,52,20,52,0,0.42,0.374,0.426,0.705,1.131,0.467,3.88
2,이정후,Hero,57,251,218,78,9,39,43,25,17,3,0.352,0.358,0.422,0.615,1.037,0.438,3.35
3,페르난데스,두산,56,262,230,88,10,50,40,22,16,0,0.375,0.383,0.443,0.583,1.026,0.442,3.12
4,배정대,KT,56,244,216,73,6,33,28,21,53,8,0.421,0.338,0.401,0.523,0.924,0.402,2.67
5,김하성,Hero,55,248,205,59,10,46,40,37,26,9,0.287,0.288,0.401,0.498,0.899,0.393,2.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,최용제,두산,1,0,0,0,0,0,0,0,0,0,-,-,-,-,-,-,-
241,최정원,NC,1,0,0,0,0,0,0,0,0,0,-,-,-,-,-,-,-
242,김현준(타),KIA,1,0,0,0,0,0,0,0,0,0,-,-,-,-,-,-,-
243,홍종표,KIA,1,0,0,0,0,0,0,0,0,0,-,-,-,-,-,-,-
244,현원회,SK,1,0,0,0,0,0,0,0,0,0,-,-,-,-,-,-,-

In [17]:
import time

In [ ]:
time.sleep()

In [13]:
# 테이블 형태이면 text도 바로 read_html로 읽을 수 있다.
import pandas as pd
pd.read_html(res.text)[0].shape

(0, 20)